### ISSUE TITLE
[REQUEST] Add Windows to Github Actions workflow

### ISSUE THREAD

**Issue by iwasakishuto** [iwasakishuto/Translation-Gummy#12]
Github Action workflow only supports **ubuntu** and **macOS**, so please add **Windows**

See [here](https://github.com/iwasakishuto/Translation-Gummy/blob/master/.github/workflows/python-package.yml).

```YAML
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.7, 3.8]
        chrome-version: ['83.0.4103.39']
        os: [ubuntu-latest, ubuntu-16.04, macos-latest]
```
