### ISSUE TITLE
[REQUEST] Create a workflow which updates the Translation-Gummy version in EC2 instance.

### ISSUE THREAD

**Issue by iwasakishuto** [iwasakishuto/Translation-Gummy#13]
It is troublesome and often causes a mistake to **manually** update the Translation-Gummy version in EC2 instance for each version update, so I would like to automate it with the Github Actions workflow.

**Describe the solution you'd like**

```YAML
on:
  release:
    types: [ created ]
```
